### ISSUE TITLE
Question de performance

### ISSUE THREAD

**Issue by W-D0n** [W-Kamal/OhMyFood_3#8]
J'ai découvert la possibilité d'utiliser une méthode pour spécifier un sélecteur sur lequel appliquer des propriétés avec une sorte de parsing : le sélecteur d'attribut.

Dans le (work in progress) fichier **_restaurants.scss** j'utilise 
```
_//utilisation du sélecteur d'attributs: ici je sélectionne l'élément de classe qui se termine par -arrow-left_
[class$='-arrow-left'] { background-color: red; }
```

### **Questionnement**
(à creuser) Est-ce une pratique efficace, bonne practice, avantageuse en terme de perf par rapport à l'addition de classe dans la balise html ? (à creuser)

**Comment by thierrylemoulec** [comment]
Oui ça à son utilité et c'est parfois utilisé dans certaines librairies. Bootstrap notamment utilisé ce type de sélecteur passé un temps (peut-être toujours). 
En règle général il n'y a pas vraiment de soucis de performance en CSS. Le plus important reste la compréhension et la lisibilité du code. Ce n'est pas rare d'utiliser ce genre de sélecteur pour par exemple ajouter des règles de layout quand une class contient col-x 
ça permet effectivement de ne pas avoir besoin de faire `<div class="col col-1">` pour avoir des styles génériques pour les colonnes, plus des spécifiques pour 1 col

**Comment by W-D0n** [comment]
Ok, c'est noté, merci pour le commentaire.
Je me posais cette question car je lisais sur les questions de perf avec les animations plutôt les transform que sur les width.
Je me demandais à quel niveau se situais ce genre de "bidouille" sur la chrono des traitements des feuilles css (functions call/recalcul style etc etc).
Et puis quoi privilégier entre cette façon de faire et celle avec les nth child...? Je m'éparpille encore.
